"""Add funding fields to beneficiaries table

Revision ID: adec844e054b
Revises: 
Create Date: 2025-07-30 09:53:46.979809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adec844e054b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funding_requested', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('funding_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('funding_status', sa.Enum('pending', 'approved', 'declined', name='funding_status'), nullable=True))
        batch_op.add_column(sa.Column('funding_approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('funding_approved_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('funding_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['funding_approved_by'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('funding_notes')
        batch_op.drop_column('funding_approved_date')
        batch_op.drop_column('funding_approved_by')
        batch_op.drop_column('funding_status')
        batch_op.drop_column('funding_amount')
        batch_op.drop_column('funding_requested')

    # ### end Alembic commands ###
